### ISSUE TITLE
Server not found

### ISSUE THREAD

**Issue by Floodnl** [athombv/nl.buienradar#16]
Hi there seems to be an issue since the last patch (1,1,9) for me using Buienradar giving an command results in the notification that the server could not be found (Sorry, kan de server niet vinden.) 

in my case i request if i need an umbrella.

**Comment by kikkerX10** [comment]
Any New on This.? Have the same problem . Have to reboot Homey and than Homey can Find the buienradar server again. But a few days later the connection is lost again

**Comment by Floodnl** [comment]
Issue currently still ongoing, in the time i addressed it did worked for a couple of weeks but now it's down again.  I use buienradar in a daily returning flow and this flow is not triggered any more for quite some time.

**Comment by nattlip** [comment]
+1

**Comment by BasKiers** [comment]
This issue should now be fixed (again) in version 2.1.1 of the app which is now available in the appstore

**Comment by Floodnl** [comment]
Correct but since no active response came, i didnt notified it was solved
