### ISSUE TITLE
Querying gpsgadget.buienradar.nl fails because host doesn't exist in DNS

### ISSUE THREAD

**Issue by bartdiaz** [athombv/nl.buienradar#21]
https://forum.athom.com/discussion/comment/60881

Hi Buienradar-app-maker,

Thanks for this app, but checking my logs I found something odd:

My DNS-server logs a lot of queries from the Buienradar-app trying to find the domain gpsgadget.buienradar.nl, but somehow added the DHCP-suffix to this request, so it will end up sending a query containing gpsgadget.buienradar.nl.thuis.local which -ofcourse- can't be resolved by the public DNS-servers. After this query it fires some new DNS-requests containing the right DNS-name, gpsgadget.buienradar.nl

Oct 24 18:50:35 dnsmasq[2122]: query[A] gpsgadget.buienradar.nl.thuis.local from 192.168.xxx.xxx
Oct 24 18:50:35 dnsmasq[2122]: query[AAAA] gpsgadget.buienradar.nl.thuis.local from 192.168.xxx.xxx

btw: I'm using Buienradar app version 2.1.2

As it seems now; gpsgadget.buienradar.nl doesn't exist, that's why the local DHCP-suffix is added.

**Comment by BasKiers** [comment]
Hi,

I've removed the gpsgadget url from the app. However these urls change quite a lot so it could be that at a later time another url will stop working or I will need to re-add the gpsgadget url. For now though it looks like that url is no longer in use so it is removed in the latest version of the app.

Regards,
Bas
