### ISSUE TITLE
Does not work on 0.8.29

### ISSUE THREAD

**Issue by bliekp** [athombv/nl.buienradar#3]
Does not react to voice triggers or flows.

**Comment by freekwebdesign** [comment]
Did the buienradar app react on your voice triggers or flows before the update to 0.8.29?

**Comment by bliekp** [comment]
I received my Homey yesterday, and it immediately went to 0.8.29, so no idea.

**Comment by freekwebdesign** [comment]
I just tested the buienradar app on a Homey with version 0.8.29 and the voice triggers seem to work correctly.

Does Homey react on your voice when you say 'Ok Homey, What time is it'?
Can you also try to go to: 'http://yourhomeyurl/manager/speech-input/' and type 'rain' into the text box and press enter. 
The buienradar app should respond with sentence saying if there is rain or not.

**Comment by bliekp** [comment]
Tried that. Does not work.
Homey does respond to other voice commands.

**Comment by freekwebdesign** [comment]
Hmm, that is strange.

What is the RAM and CPU usage of the .nl.buienradar app?
You can find this under 'settings' --> 'developers'.
For me the RAM usage is constantly 32MB and the CPU is 0%, and when the speech is triggered the CPU usage is for about 5 seconds around 10%.

If you have not tried that yet; can you try to reboot Homey and reinstall the buienradar app?

**Comment by bliekp** [comment]
A reinstall of the app solved it. Weird!
Issue can be closed.
