### ISSUE TITLE
Doens't work stable. I did some testing with it.

### ISSUE THREAD

**Issue by westd05** [athombv/nl.buienradar#5]
0.8.29 
Buienradar App 1.1.6
English
2 apps installed, KilkAanKlikUit, Buienradar.

13:36:
After a reinstall the first 2 voice command worked.
"When will it start raining?", 
"When will it stop raining?", 

When I try
"Is it raining right now?"
It doesn't work anymore. Even the 2 commands that did work before do not work anymore.
It starts (white ring is circling a few times) and then it stops. No voice reply.

13:40 Removed the app.

13:41 Reinstalled app
"When will it start raining?",  : Worked fine.
"Is it raining right now?" : Didn't work.
"When will it start raining?",  : Didn't work anymore.

13:45 Removed the app again.

13:46 Reinstalled the app again.
"When will it stop raining?",  Worked fine.
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked fine.
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked fine.
"When will it start raining?",  Worked fine.
(13:49)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (No there is no Rain expected in 2 hrs)
"When will it start raining?",  Worked. (there is no Rain expected in 2 hrs)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (No there is no Rain expected in 2 hrs)
(13:53)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (No, there is no rain right now)
"When will it start raining?",  Worked. (No there is no Rain expected in 2 hrs)
"When will it start raining?",  Worked. (No it will not start rainingin now.)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it STOP raining?",  Didn't work.
14:01
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?", Worked. (there is no Rain expected in 2 hrs)
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.
"When will it start raining?",  Didn't work.
"When will it start raining?",  Didn't work.
14:05
"When will it start raining?",  Didn't work.
"When will it start raining?",  Didn't work.
------ Waiting 2 mins.-----
14:07
"When will it start raining?",  Didn't work.
"When will it start raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.
"When will it start raining?",  Didn't work.
"Is it raining right now?",  Didn't work.
"Is it raining right now?",  Didn't work.
"Is it raining right now?",  Didn't work.
"When will it start raining?",  Didn't work.
14:12
------Waiting 8 minutes.-----
14:20
"When will it start raining?",  Didn't work.
"When will it start raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?",  Didn't work.

14:21
Disabled App
"When will it start raining?",  Didn't work.
Enabled App
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (No there is no Rain expected in 2 hrs)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (There is no Rain expected in 2 hrs)
"When will it STOP raining?",  Didn't work.
"When will it STOP raining?",  Worked. (There is no Rain expected in 2 hrs)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Didn't work.

14:28
Disabled App. Wait 30 seconds then Enabled App.
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (There is no Rain expected in 2 hrs)
Disabled App. Wait 30 seconds then Enabled App. Wait 30 seconds.
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
"When will it start raining?",  Worked. (There is no Rain expected in 2 hrs)
"When will it start raining?",  Worked. (No there is no Rain expected in 2 hrs)
"When will it start raining?",  Didn't work.
"When will it start raining?",  Worked. (It will not start raining in 2 hrs)
14:35 END

**Comment by freekwebdesign** [comment]
Thanks for the extensive testing.

Can you try to 'say' these voice-commands by typing the voice commands by using this url  'http://YOUR-HOMEY-ADDRESS/manager/speech-input/'?
Afterwards you can 'hear' the response of Homey by looking at: 'http://YOUR-HOMEY-ADDRESS/manager/speech-output/'

Where you need to replace 'YOUR-HOMEY-ADDRESS' with the address of your Homey.
Is the behavior still the same?

**Comment by westd05** [comment]
I tried Dutch this time. I assume you're Dutch too. So I reply in Dutch. If
I'm wrong, please let me know and I'll translate it.

Input via typen gaat beter. De issues lijken dus wat meer in de speech van
homey te zitten.
Er viel me nog wel een ander issue op. Dat is bij de vraag "gaat het
vandaag regenen?" Zie de testresultaten hieronder.
De app moet dan herstart worden om weer te functioneren.

Homey 0.8.32 Buienradar APP 1.1.6
VRAAG ANTWOORD
regen nee, er is nee regen nu  (vreemde reply)
wanneer gaat het regenen ja, er is gemiddelde regen verwacht in 54 minuten.
wanneer stopt het regenen nee, er wordt geen regen verwacht om 2 uren
verwacht je regen nee, er is nee regen nu (vreemde reply)
gaat het vandag regenen buienradar kan alleen voorspellingen 2 uur vooruit
doen, vraag alsjeblieft je nog een keer maar dan binnen twee uur. (ik geef
geen 2e antw.)
komt er regen (geen antwoord)
komt er regen (geen antwoord)
wanneer gaat het regenen (geen antwoord)
----APP uitgeschakeld, APP weer ingeschakeld-------
wanneer gaat het regenen ja, er is gemiddelde regen verwacht in 43 minuten.
komt er regen ` nee, er is nee regen nu  (vreemde reply)
gaat het vandag regenen buienradar kan alleen voorspellingen 2 uur vooruit
doen, vraag alsjeblieft je nog een keer maar dan binnen twee uur. (ik geef
geen 2e antw.)
wanneer gaat het regenen (geen antwoord)
wanneer gaat het regenen (geen antwoord)
----APP uitgeschakeld, APP weer ingeschakeld-------
wanneer gaat het regenen ja, er is gemiddelde regen verwacht in 37 minuten.
wanneer gaat het regenen ja, er is gemiddelde regen verwacht in 37 minuten.
wanneer gaat het regenen ja, er is gemiddelde regen verwacht in 32 minuten.


Groeten David

**Comment by freekwebdesign** [comment]
Thanks for trying it by typing the voice commands.
The speech recognition is indeed sometimes not accurate enough, which will sometimes result in incorrect results.

I am indeed also Dutch, so the Dutch output is no problem for me. ;-)
The Dutch output is a bit rough at the moment because the text-parser is based on the English version of the app. At the moment I am working on building a proper Dutch text-parser for the next version of the app.
The issue that the app doesn't respond will also be fix in the next version.

**Comment by westd05** [comment]
Great to hear! Thanks. And thanks for the great app!
If you need me to test something, please let me know.

Regards David.

Op di 3 mei 2016 10:20 schreef freekwebdesign <notifications@github.com>:

**Comment by freekwebdesign** [comment]
@westd05 The app is updated to version 1.1.7, which should solve your issues!
