### ISSUE TITLE
Request: Buienradar 'then-card'

### ISSUE THREAD

**Issue by Keverjeroen** [athombv/nl.buienradar#7]
Hi,

Not an issue, but a request. It would be great if the Buienradar app had an 'then-card'. This would make ik possible to trigger the app with other input-commands. Examples:

- When: specific user came home -> Then: Let Buienradar tell if it is going to rain
- When: button is pushed ->  Then: Let Buienradar tell if it is going to rain
etc.

**Comment by WeeJeWel** [comment]
I think I'm going to add a 'simulate speech' card in Homey, which will
achieve this and much more.
